Create multiple_parkpow.py
parkpow/deep-license-plate-recognition pull request #110
Opened 2023-04-16 23:50 UTC by ttayson

2023-04-17 13:41 UTC, danleyb2 requested changes

2023-04-17 13:41 UTC, danleyb2 commented on multiple_parkpow.py
> +from flask import Flask, request, jsonify
List Dependencies in `pyproject.toml`

2023-04-17 13:41 UTC, danleyb2 commented on multiple_parkpow.py
> +        response = requests.post(set_parkpow[camera_id]["url"], headers=headers, files={"upload": (filename, file.read())}, data={"json": original_data})
Add a `try...catch` in case the request fails.
show an error message and return a correct status code to snapshot to trigger a retry

2023-04-17 13:41 UTC, danleyb2 commented on multiple_parkpow.py
- [ ] Run `pre-commit` using git hook to standardize code style

2023-04-17 13:41 UTC, danleyb2 commented on multiple_parkpow.py
> +        if not file:
should  this come before checking for the filename above?

2023-04-20 01:56 UTC, ttayson commented on multiple_parkpow.py
> +from flask import Flask, request, jsonify
Done

2023-04-20 01:58 UTC, ttayson commented
@danleyb2 please see if this is now correct.

2023-04-20 05:57 UTC, danleyb2 commented
@ttayson you should also commit `poetry.lock`

2023-04-20 06:02 UTC, danleyb2 requested changes
@ttayson  @marcbelmont LGTM after fixing 2 more comments

2023-04-20 06:02 UTC, danleyb2 commented on multiple_parkpow.py
> +            return None, response.status_code
@ttayson 
I don't think a [ConnectionError](https://requests.readthedocs.io/en/latest/api/#requests.ConnectionError) will have a `response.status_code`

2023-04-21 00:43 UTC, ttayson commented
> @ttayson you should also commit `poetry.lock`

Sorry Brian, I added it manually, I am not familiar with poetry

2023-04-24 23:02 UTC, ttayson commented
@danleyb2 please check again

2023-04-25 03:04 UTC, danleyb2 commented
@ttayson Let's use Python logger instead of print, It allows setting log levels

2023-04-27 02:30 UTC, ttayson commented
@danleyb2  please check again

2023-04-27 14:47 UTC, danleyb2 approved these changes
@ttayson @marcbelmont looks good to me

2023-04-27 16:41 UTC, merged