Simplify blur
parkpow/deep-license-plate-recognition pull request #137
Opened 2023-08-03 09:52 UTC by AashishDhakal

2023-08-03 10:24 UTC, danleyb2 requested changes

2023-08-03 10:24 UTC, danleyb2 commented on video-editor/docker-compose.yml
> +      - SDK_URL=http://alpr:8080
video-editor does not need **SDK_URL**

2023-08-03 13:57 UTC, AashishDhakal commented
@marcbelmont @danleyb2 By default the docker compose appends prefix to the volume. For example, if not used external:true, the volume will be created as video-editor_license, and causes issues for the machines which has Snapshot SDK installed previously.

So, here are the steps:

If the machine has Snapshot SDK installed previously:
`docker-compose up --build`

Else:
`docker volume create license`
`docker-compose up --build`

2023-08-04 07:25 UTC, danleyb2 commented
@AashishDhakal I prefer making the default option to be storing the license in an external volume so it's easier for a user to re-use existing licenses

@marcbelmont LGTM

2023-08-04 07:25 UTC, danleyb2 approved these changes

2023-08-04 08:25 UTC, marcbelmont commented
LGTM

2023-08-04 08:25 UTC, merged

2023-08-06 11:04 UTC, AashishDhakal commented
@marcbelmont I think I don't have access to the docs repo.

2023-08-06 11:21 UTC, marcbelmont commented
@AashishDhakal 

I just added you