Added multi_step_lookup.py
parkpow/deep-license-plate-recognition pull request #165
Opened 2023-12-13 02:43 UTC by dev-bon

Added multi_step_lookup.py script

- Added output parameters to output either json and csv
- Also implemented adding of drawing of bounding boxes for image results

2023-12-13 08:20 UTC, marcbelmont commented
@dev-bon, it would be good to have this feature directly in https://github.com/parkpow/deep-license-plate-recognition/blob/master/plate_recognition.py
Can you do that next?

2023-12-15 17:40 UTC, marcbelmont commented on plate_recognition.py
> +            results.append(process_image(path, args, engine_config))
I would rather separate the implementation into `process_full_image` and `process_split_image`. The code for `args.show_boxes` can remain in `main`. This makes the single image process simpler to read and understand.

2023-12-15 22:08 UTC, dev-bon commented on plate_recognition.py
> +            results.append(process_image(path, args, engine_config))
Got this, sure will refactor this Sir.

2023-12-18 11:06 UTC, marcbelmont requested changes

2023-12-18 11:06 UTC, marcbelmont commented on plate_recognition.py
> +            annotated_image = draw_bb(image, results["results"], None, text_function)
`results` is a list with one element per file. I believe we just want the last one.

```suggestion
            annotated_image = draw_bb(image, results["results"][-1], None, text_function)
```

2023-12-18 11:06 UTC, marcbelmont commented on plate_recognition.py
> +        if args.show_boxes or args.annotate_images and "results" in results:
```suggestion
        if (args.show_boxes or args.annotate_images) and "results" in results[-1]:
```
what do you think?

2023-12-18 11:06 UTC, marcbelmont commented on multi_step_lookup.py
Let's remove this file since the functionality is now in the main script.

2023-12-18 23:02 UTC, dev-bon commented on plate_recognition.py
> +            annotated_image = draw_bb(image, results["results"], None, text_function)
This causes errors Sir, tried to have this but the error is: TypeError: string indices must be integers

based on usage, draw_bb is a function that expects a list

2023-12-18 23:03 UTC, dev-bon commented on plate_recognition.py
> +        if args.show_boxes or args.annotate_images and "results" in results:
Same goes for this, results should be a list.

2023-12-18 23:06 UTC, dev-bon commented on multi_step_lookup.py
Removed it now sir, I had also placed the annotating in a function, revisited my code and it does not output images, it works now this way.

https://github.com/parkpow/deep-license-plate-recognition/blob/08281c0151398b31c51230a920c63cb8240e42da/plate_recognition.py#L352

2023-12-19 11:10 UTC, marcbelmont commented on plate_recognition.py
>      if args.output_file:
did you check if this parameter works when combined with `--split-image`?

2023-12-19 12:44 UTC, dev-bon commented on plate_recognition.py
>      if args.output_file:
Yes, works with and without the parameter Sir

2023-12-19 13:24 UTC, marcbelmont approved these changes

2023-12-19 13:24 UTC, merged