feat: send webhooks to salient CompleteView events
parkpow/deep-license-plate-recognition pull request #179
Opened 2024-02-16 07:42 UTC by danleyb2

2024-02-20 13:57 UTC, marcbelmont requested changes
- [x] move to webhooks
- [ ] merge Salient and NX

2024-02-22 09:47 UTC, marcbelmont commented
@danleyb2 
Don't forget to work on this.

2024-02-23 15:18 UTC, adolfoarmas reviewed
Regarding the folder organization:

I propose the organization on webhooks VMS to be:

webhooks -> VMS -> 
- NX_or_Salient _(this forwarder)_
- OpenEye
- Synology

That way all VMS/VMM integrations are bundled in one folder.

2024-02-23 15:18 UTC, adolfoarmas commented on webhooks/forwarder/destinations/salient.py
> +            lgr.error("OOps: Something Else", err)
NIT:
```suggestion
            lgr.error("Oops: Something Else", err)
```

2024-02-23 15:18 UTC, adolfoarmas commented on webhooks/forwarder/destinations/nx.py
> +            lgr.error("OOps: Something Else", err)
NIT:
```suggestion
            lgr.error("Oops: Something Else", err)
```

2024-02-23 15:18 UTC, adolfoarmas commented on webhooks/forwarder/destinations/nx.py
> +            lgr.error("OOps: Something Else", err)
Kindly confirm:
- Which exception collects the metadata "camera" name error?
- Is the error coming from the API explanatory enough regarding the wrong camera name for example?
- Same questions for Salient deviceGuid.

2024-02-23 15:42 UTC, danleyb2 commented
@adolfoarmas regarding the folder structure, The larger idea is to also add OpenEye and Synology as a destination in the **forwarder**. This is because they are all basically a server that format the webhook payload then call and external API

2024-02-25 13:48 UTC, ttayson commented
@marcbelmont @danleyb2 
I have only one point to highlight: I suggest the creation of bookmarks instead of events, along with the use of the latest NX API that does not require Digest authentication. The use of bookmarks makes the boards searchable in the system, in addition to providing a newer and recommended authentication method.

We have two NX implementations in our guides. The implementation below utilizes bookmarks:
https://github.com/parkpow/deep-license-plate-recognition/tree/master/webhooks/Webhook_nx

Is there any limitation for using bookmarks that made us choose events instead?

2024-02-26 19:16 UTC, danleyb2 commented
@ttayson @marcbelmont  @adolfoarmas 
Suggestions:
- [ ]  Keep existing REST API **NX implementation**  and delete the one in PR
- [ ]  Maintain the implementations in separate folders and so refactor this PR to only contain Salient

Question:
How should we handle support for different NX VMS versions because the endpoint changes? It's easier and recommended to support latest only then advise users to upgrade 

Based on **NX API versions and their support** from [here](https://meta.nxvms.com/doc/developers/api-tool/main?type=1&system=7)
_If the integration intends to support VMS 5.0+, it must prefer `/rest/v1` which was introduced in this VMS version. 
If it intends to support VMS 5.1+, it must prefer `/rest/v2`, and so on. 
Originally (up to and including VMS 4.2), there was a mostly procedural-style API, with URLs mostly starting with `/api/` and `/ec2/` - these functions are now referred to as a "LEGACY & BETA" API.
Latest is `/rest/v3`_

2024-02-28 15:41 UTC, adolfoarmas commented on webhooks/webhook_salient/main.py
> +                        # "streamId": 0
NIT: remove if not needed.

```suggestion
```

2024-02-28 15:41 UTC, adolfoarmas commented on webhooks/webhook_salient/main.py
> +    parser.add_argument("--vms", help="Recording Server API Endpoint.", required=True)
```suggestion
    parser.add_argument("--username", help="Salient VMS Username.", required=True)
    parser.add_argument("--password", help="Salient VMS Password.", required=True)
    parser.add_argument("--vms_api_url", "-v" help="Salient VMS API Endpoint.", required=True)
```

The `vms` variable name will have to be changed in other lines of code.

2024-02-28 15:41 UTC, adolfoarmas commented on webhooks/webhook_salient/README.md
> +       --vms='http://localhost:4502' \  # Recording server API Endpoint
```suggestion
       --vms_api_url='http://localhost:4502' \  # Recording server API Endpoint
```

2024-02-28 15:41 UTC, adolfoarmas commented on webhooks/webhook_salient/README.md
> +       --vms='http://192.168.100.6:4502' \
```suggestion
       --vms_api_url='http://192.168.100.6:4502' \
```

2024-02-29 14:20 UTC, marcbelmont approved these changes

2024-02-29 14:20 UTC, merged