Fix the indentation error and the timestamp parsing error
parkpow/deep-license-plate-recognition pull request #191
Opened 2024-03-20 06:05 UTC by kevinchan123456

2024-03-20 19:12 UTC, danleyb2 requested changes

2024-03-20 19:12 UTC, danleyb2 commented on webhooks/Synology/requirements.txt
> +certifi==2023.7.22 ; python_version >= "3.10" and python_version < "4.0"
Specify only the the direct dependencies `requests==2.31.0` and `python-dateutil==2.8.2` which will then install the others. Makes it easier to upgrade

2024-03-20 19:12 UTC, danleyb2 commented on webhooks/Synology/middleware_webhook_rest.py
> +	def is_timestamp(self, s):
indentation should use spaces instead of tabs, Run `pre-commit` to fix

2024-03-21 02:49 UTC, kevinchan123456 commented on webhooks/Synology/requirements.txt
> +certifi==2023.7.22 ; python_version >= "3.10" and python_version < "4.0"
I've updated my commit, thanks for your reply.

2024-03-21 02:50 UTC, kevinchan123456 commented on webhooks/Synology/middleware_webhook_rest.py
> +	def is_timestamp(self, s):
Sure, I'll undo the commit that adjusted the indentation.

2024-03-21 04:13 UTC, adolfoarmas commented on webhooks/Synology/middleware_webhook_rest.py
> +                return
I think this can be more readable, Is it possible to test? :

```python
def is_valid_datetime_format(datetime_str):
    try:
        dp.parse(datetime_str)
        return True
    except ValueError:
        return False

def is_unix_timestamp(timestamp_str):
    try:
        int(timestamp_str)
        return True
    except ValueError:
        return False

def is_required_timestamp_type(datetime_str):
    if is_valid_datetime_format(datetime_str):
        return False
    elif is_unix_timestamp(datetime_str):
        return True
    # If neither a datetime format nor a Unix timestamp
    return False

def forward_to_rest_service(self, json_data, image_base64):
    url = os.getenv('REST_SERVICE_URL')

    # The data from the plate regognizer
    timestamp = json_data['data']['timestamp_local']
    plate = json_data['data']['results'][0]['plate']
   
    if not self.is_required_timestamp_type(timestamp):
        try:
            parsed_date_time = dp.parse(timestamp)
            timestamp = str(int(parsed_date_time.timestamp()))
        except ValueError:
            print("\033[31mERROR:    Invalid timestamp format.%s\033[0m", timestamp)
            return         
```

2024-03-21 05:51 UTC, kevinchan123456 commented on webhooks/Synology/middleware_webhook_rest.py
> +                return
Sure, I will test these refactored changes.

2024-03-21 06:37 UTC, kevinchan123456 commented on webhooks/Synology/middleware_webhook_rest.py
> +                return
I've updated my commit that is based on your pseudocode.
It passed the test.

2024-03-21 14:42 UTC, adolfoarmas approved these changes

2024-03-21 17:01 UTC, danleyb2 requested changes

2024-03-21 17:01 UTC, danleyb2 commented on webhooks/Synology/middleware_webhook_rest.py
> +        elif self.is_unix_timestamp(datetime_str):
The  **"timestamp_local"** sent by web-hooks always in this format **"2021-10-27 06:20:55.161444+00:00"** ?
There is no need to attempt parsing as a unix timestamp.

You could also use included **"timestamp"** which is in this format **"2021-10-27T06:20:55.161444Z"**

2024-03-22 01:31 UTC, kevinchan123456 commented on webhooks/Synology/middleware_webhook_rest.py
> +        elif self.is_unix_timestamp(datetime_str):
The reason we need to parse the time into a unix timestamp is because our app requires this format.

2024-03-22 07:24 UTC, danleyb2 commented on webhooks/Synology/middleware_webhook_rest.py
> +        elif self.is_unix_timestamp(datetime_str):
@kevinchan123456 What i mean is we don't need `is_required_timestamp_type` and `is_unix_timestamp` function and we should just call ` dp.parse(datetime_str)` directly

2024-03-22 07:30 UTC, kevinchan123456 commented on webhooks/Synology/middleware_webhook_rest.py
> +        elif self.is_unix_timestamp(datetime_str):
I see. I will update the commit as soon as I can.

2024-03-22 08:11 UTC, kevinchan123456 commented on webhooks/Synology/middleware_webhook_rest.py
> +        elif self.is_unix_timestamp(datetime_str):
Please check again.
I've tested the latest version of the code.

2024-03-22 08:13 UTC, danleyb2 approved these changes

2024-03-22 08:42 UTC, merged