feat: webhook middleware
parkpow/deep-license-plate-recognition pull request #212
Opened 2024-09-03 04:09 UTC by AashishDhakal

2024-09-03 04:12 UTC, AashishDhakal commented
@marcbelmont I am almost done. I made the common webhook consumer based on the synology code, but I see `json` key being indexed, https://github.com/parkpow/deep-license-plate-recognition/blob/master/webhooks/Synology/middleware_webhook_rest.py#L80

Is this outdated or we actually have that key on our webhooks? I didn't see that key on the webhook.

2024-09-03 07:48 UTC, marcbelmont commented
@AashishDhakal here's the doc about the `json` field. https://guides.platerecognizer.com/docs/stream/results#vehicle-information

2024-09-04 04:20 UTC, AashishDhakal commented
@marcbelmont It should be ready for review then.

2024-09-04 06:33 UTC, marcbelmont requested changes
- [ ] rename to webhooks/middleware
- [ ] rename to webhooks/middleware/protocols

2024-09-04 06:33 UTC, marcbelmont commented on webhook-middleware/README.md
Use better titles. For example, REST Protocol instead of Middleware 1.

2024-09-04 06:33 UTC, marcbelmont commented on webhook-middleware/middlewares/nx.py
> +        return f"Failed to process the request: {err}", 500
Isn't the caller expecting a single value? Please add types to all `process_request` definitions for robustness.

2024-09-04 06:33 UTC, marcbelmont commented on webhook-middleware/consumer.py
> +from http.server import BaseHTTPRequestHandler, HTTPServer
The requirements include Flask. Do you want to switch to that?

2024-09-05 00:58 UTC, ttayson commented
Everything seems correct and intuitive in how we are handling the different integrations.
I would like a little more time to test the integrations, especially the main ones.

@marcbelmont  Regarding the guide: will we have this Docker image directly from the Platerecognizer repository?

As for the other integration procedures (ex: Stream Config.ini), are we going to centralize them in another location, or will we transfer them to our guide? Similar to:  https://guides.platerecognizer.com/docs/parkpow/integrations

2024-09-05 07:14 UTC, marcbelmont commented
@ttayson @AashishDhakal 
Yes, the image will be hosted on Docker Hub. What's a good name for the image?  
The documentation and examples should be on Guides. That is more user-friendly than GitHub, which may scare some people off.

2024-09-05 07:36 UTC, marcbelmont commented on webhooks/middleware/protocols/crop_plate.py
> +        return "Webhook request failed."
On failure, the consumer will still return a 200. It should instead return a 400. We can either return multiple values or throw a specific exception. This issue exists in other files as well.

2024-09-05 07:38 UTC, marcbelmont commented on webhooks/middleware/requirements.txt
> +waitress==2.1.2
Waitress is not being used. It should serve the Flask app.

2024-09-05 13:53 UTC, marcbelmont commented on webhooks/middleware/requirements.txt
> -waitress==2.1.2
if we don't use waitress, don't we get a warning about Flask running in Dev mode or something?

2024-09-05 14:04 UTC, AashishDhakal commented on webhooks/middleware/requirements.txt
> -waitress==2.1.2
We do. I will bring it back and serve with waitress.

2024-09-06 01:53 UTC, ttayson commented
> @ttayson @AashishDhakal Yes, the image will be hosted on Docker Hub. What's a good name for the image? The documentation and examples should be on Guides. That is more user-friendly than GitHub, which may scare some people off.

As an alternative and for greater clarity, I suggest text that includes: integrations, Addons, stream-gateway, or stream-integration

I will add an "integrations" category to the stream's sidebar in the guide and transcribe what's necessary.

2024-09-06 06:50 UTC, marcbelmont requested changes
- Support for `Synology/` is missing

2024-09-08 17:03 UTC, mahmoudsadeq commented
Can you guide me to where the front end is? @marcbelmont

2024-09-08 19:31 UTC, ttayson commented
@AashishDhakal @marcbelmont, I’m testing some integrations and noticed a limitation in the NX integration. The bookmarks are being created normally, but the import of Parkpow tags, if the user uses them, is not being performed. The function parkpow_get_tags() is not being triggered.

It is possible to work around this issue. In the previous code, it was called in the main function, but now it would be costly to call this function with every detection.

2024-09-09 11:03 UTC, AashishDhakal commented
> * Support for `Synology/` is missing

@marcbelmont That's rest protocol.

2024-09-10 04:10 UTC, AashishDhakal commented
> @AashishDhakal @marcbelmont, I’m testing some integrations and noticed a limitation in the NX integration. The bookmarks are being created normally, but the import of Parkpow tags, if the user uses them, is not being performed. The function parkpow_get_tags() is not being triggered.
> 
> It is possible to work around this issue. In the previous code, it was called in the main function, but now it would be costly to call this function with every detection.

@ttayson Can you please test it again? I have updated the code.

2024-09-11 01:10 UTC, ttayson commented
@marcbelmont @AashishDhakal I tested the NX function again, and everything is okay.
I also tested the crop_plate function, but I only got a cropped image when image_type = original. When image_type = vehicle, the cropped image doesn't work. I believe this is a limitation of the stream, which continues to send the plate box in its original size.

I can't test the other protocols directly, but they are simpler codes, just for conversion. It seems okay.

2024-09-11 01:11 UTC, ttayson approved these changes

2024-09-11 10:38 UTC, merged